### PR TITLE
Add HAProxy 2.9

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by tianon** [comment]
(rebased for #210 :sweat_smile:)

**Comment by TimWolla** [comment]
Oh, did the branches conflict? I hoped that I would be able to avoid it by carefully crafting them. Thanks for the rebase!

**Comment by tianon** [comment]
Yeah, they were _just_ close enough in `versions.json` to conflict :sweat_smile:

**Comment by tianon** [comment]
The PRs are appreciated! :bow: :+1:

**Pull request merged**
