### PR TITLE
add 2.3-dev0

### PR DESCRIPTION
**Pull request by tao12345666333**

### CODE REVIEW

**Comment by tianon** [comment]
Looks good, thanks! :+1:

**Comment by TimWolla** [comment]
I'm probably way too late here, but I don't consider this a good idea. 

2.3-dev0 is 100% equivalent to a 2.2.0 and there is no regular release schedule for the -devX versions until shortly before the gold release (for a fitting definition of shortly). There's a reason I'm only ever adding the -devX versions a month or two before the expected gold release.

**Comment by tianon** [comment]
Arg, whoops; good catch.  Not too late, we'll just roll this back.

**Comment by tao12345666333** [comment]
> 2.3-dev0 is 100% equivalent to a 2.2.0 and there is no regular release schedule for the -devX versions until shortly before the gold release (for a fitting definition of shortly).

You're right. Usually when we release `-dev1`, it will be announced.

The addition of `2.3-rc` here is to prepare for the subsequent 2.3.x, so that when the subsequent dev version is released, it can be updated as soon as possible. And, when we released `-dev1`, we compared with `-dev0` what 2.2.x changed, instead of 2.2.x. This is why I added `2.3-dev0` directly.

Of course, if you want to avoid confusion, you can choose to add `2.3-rc` to `-dev1` or even later.

**Comment by tianon** [comment]
Isn't `-dev0` a snapshot, not a normal "release" ?

**Comment by tianon** [comment]
If it's a normal "release" in the sense that it won't change over time, we should leave it, but if it's a snapshot, we should go forward with #122.

**Comment by tao12345666333** [comment]
yes, it won't change over time. https://github.com/haproxy/haproxy/releases/tag/v2.3-dev0

**Comment by tao12345666333** [comment]
Although it may not be a "general release" (no special announcement)

**Comment by tianon** [comment]
We had a chat with upstream on IRC and landed on https://github.com/docker-library/haproxy/pull/123. :+1:

**Comment by tao12345666333** [comment]
Thanks！@tianon

**Pull request merged**
