### PR TITLE
Add HAProxy 2.0-rc (2.0-dev3)

### PR DESCRIPTION
**Pull request by TimWolla**
Final release is planned for the end of the month: https://www.mail-archive.com/haproxy@formilux.org/msg33781.html

This pull request serves as a first smoke test, I don't expect any breakage, though.

---

I'd like to point out this paragraph from #79 as well:

> It should also be evaluated whether the haproxy:1 alias makes sense. The next version will be called 2.0 while not making any breaking changes to the best of my knowledge.

We should think about dropping `haproxy:1` and `haproxy:2` aliases and instead only provide `:latest` and the various “minor” versions. HAProxy 2.1 will remove some long-deprecated configuration options, though: https://www.mail-archive.com/haproxy@formilux.org/msg33580.html

### CODE REVIEW

**Comment by TimWolla** [comment]
Oh, Travis does not run on draft PRs? :pensive:

**Comment by tianon** [comment]
Nice!  Should `USE_GETADDRINFO` be added in Alpine as well?  Or is that function in `musl` not sufficient for HAProxy's usage?

**Comment by tianon** [comment]
Also, :+1: to dropping the `haproxy:1` alias.

**Comment by tianon** [comment]
I guess on second thought, maybe it makes sense to just not add `haproxy:2`, and let `haproxy:1` die slowly? (in case users are still using it?)

**Comment by TimWolla** [comment]
> Nice! Should `USE_GETADDRINFO` be added in Alpine as well? Or is that function in `musl` not sufficient for HAProxy's usage?

I have no idea. There is a simple reason it was not added to Alpine, though: I forgot. I've amended the commit, force pushed and let Travis see whether it compiles. Afterwards I guess we'll wait for a user reporting issues :innocent: 

> I guess on second thought, maybe it makes sense to just not add `haproxy:2`, and let `haproxy:1` die slowly? (in case users are still using it?)

Good question. Will removing the alias *fail* pulls or will it just no longer update? If it fails pulls I suggest to remove it, because people will notice. If it just no longer updates then I suggest that `haproxy:1` remains to ensure that people still receive bugfixes.

**Comment by tianon** [comment]
> Good question. Will removing the alias _fail_ pulls or will it just no longer update? If it fails pulls I suggest to remove it, because people will notice. If it just no longer updates then I suggest that `haproxy:1` remains to ensure that people still receive bugfixes.

It will just no longer update, so we should hang onto it. :+1:

**Pull request merged**
