### PR TITLE
Update to Debian bookworm

### PR DESCRIPTION
**Pull request by yosifkit**
Leaving `2.0` on Debian buster: https://github.com/docker-library/haproxy/pull/167

### CODE REVIEW

**Comment by tianon** [comment]
This comes with a bump to OpenSSL 3, which might cause some breakage, so we might want to pause and consider / solicit opinions. :thinking:

**Comment by TimWolla** [comment]
> which might cause some breakage,

Not breakage, but a steep loss of performance that is likely unacceptable to many users. See https://www.mail-archive.com/haproxy@formilux.org/msg43306.html (and basically the whole thread).

**Comment by TimWolla** [comment]
Also Ctrl+F "OpenSSL" and "wolfSSL" in this email: https://www.mail-archive.com/haproxy@formilux.org/msg43600.html

**Comment by TimWolla** [comment]
Ah and one more thing: OpenSSL 3 is only officially supported as of HAProxy 2.6.x, as per the list on haproxy.org:

> version 2.6 : QUIC/HTTP3, OpenSSL 3.0, better usability, improved code accessibility and maintenance

**Comment by Darlelet** [comment]
FYI: alpine image already did the openssl3 bump with https://github.com/docker-library/haproxy/commit/95fe4acadbc54495913fc1361daedfc65df2a3a6
([3.16](https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.16&repo=&arch=&maintainer=) vs [3.17](https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.17&repo=&arch=&maintainer=))

**Comment by tianon** [comment]
Yeah, oops -- that was a while ago though (a full year now).

According to https://github.com/haproxy/haproxy/issues/1276, the OpenSSL 3 support was backported to the 2.4 line, so that explains that (and we pin 2.0 to Debian Buster and Alpine 3.16 already), but that doesn't explain why 2.2 appears to be just fine. :shrug:

I guess we should probably revert 2.2 to Alpine 3.16, pin it to Debian Bullseye (to be on the safe / "upstream supported" side), and then finally do this update.

**Comment by tianon** [comment]
(first, a rebase)

**Pull request merged**
