### PR TITLE
Add syslog->stdout gateway

### PR DESCRIPTION
**Pull request by klausenbusk**

### CODE REVIEW

**Comment by klausenbusk** [comment]
Waiting for #17 to be merged.. Then I do a rebase, and fix stuff :)

**Comment by tianon** [comment]
I'm definitely not a fan of just launching `syslogd` in the background (and hoping it stays up and working and doesn't conflict with any bind-mounts the user supplies like `/dev/log` from the host). :disappointed:

Is there really no other way to accomplish this? :cry:

**Comment by klausenbusk** [comment]
> doesn't conflict with any bind-mounts the user supplies like /dev/log from the host

We can fix that by doing `[ ! -S /dev/log ]`.

> and hoping it stays up and working

The script kill everything if it exit, should we run it in a loop or what do you prefer?

> Is there really no other way to accomplish this? :cry:

Not that i'm aware :/

**Comment by Wrumm** [comment]
Hi,
I tried to test the patch and didn't get logging to work. I think I am missing something easy here. Can you tell me, how ha-proxy has to be configured and where exactly I can see the log output then?

Best

**Comment by klausenbusk** [comment]
Hi @Wrumm, you need to add something like `log /dev/log local2 info` to your `haproxy.cfg`
```

**Comment by cirocosta** [comment]
Still no better solution, right? :( I'm facing a similar issue with one of my images. What people are doing out there? Any tips?

**Comment by yosifkit** [comment]
I realized we should revisit this. When I just adding syslog to the background, it becomes a child of the `haproxy-systemd-wrapper` and then `SIGINT` and `SIGTERM` no longer stop the container. :confused:

I think we'll have to go either a complicated shell script to monitor the two daemons or go the whole way to just use a process manager and my research so far leads me to [`s6`](http://www.skarnet.org/software/s6/overview.html) since it will actually forward signals to its children.

**Comment by yosifkit** [comment]
Closing old issue in favor of discussion on https://github.com/docker-library/haproxy/pull/39.

**Pull request closed without merging**
