### PR TITLE
✨ Add syslogd option by environment variable

### LINKED ISSUE #23: Cannot find logging
It is possible to get logging of HAProxy from the container?

### PR DESCRIPTION
**Pull request by Yajo**
If you run the image with `-e SYSLOGD=1`, you will get logs! Existing deployments will see no difference.

Of course, to get the logs, you need to configure HAProxy with:

```
global
    log /dev/log local0 info
defaults
    log global
```

... or similar.

This is somewhat inspired by #19 and fixes #23.

### CODE REVIEW

**Comment by yosifkit** [comment]
I had tried this solution but it has two problems. There is nothing watching the syslogd process to ensure it stays running, so it could crash and you would no longer get any logs. Then, because syslog is technically the child of `haproxy-systemd-wrapper`, it fails to stop haproxy on `SIGINT` because it is waiting for this other child to stop that never gets sent the stop signal (this would force `docker stop` to just kill it after the 10 second timeout).

To work around these I tried setting up a minimal init in the container using `s6`, but it got far too complicated with too many custom shell scripts and broken edge cases.  I did look at many other init systems but most of them would not forward signals to haproxy so that `docker kill -s HUP` works for reloading config.

I have since gone the route of writing a small go application that forwards signals, reaps children, and listens on the syslog socket to print to std out, but I am not quite ready to propose adding it to these images since it needs more testing to ensure it does everything it is supposed to. It is over here: https://github.com/yosifkit/syslog-init.

**Comment by Yajo** [comment]
> because syslog is technically the child of haproxy-systemd-wrapper, it fails to stop haproxy on SIGINT because it is waiting for this other child to stop that never gets sent the stop signal (this would force docker stop to just kill it after the 10 second timeout).

Hi, thanks for the insight but, although in theory it could make sense, in reality this is simply not true, just because this little bash command: [`exec`](https://github.com/docker-library/haproxy/pull/39/files#diff-6f9319ba015fc2c751625f725e977217R19).

Using `exec` instructs the shell to use the following command *as a replacement of currently-ongoing process*, so the `sh` process ends and gets converted into the `haproxy` one.

See, there's a patched `haproxy:1.7-alpine` container running in another terminal, called `proxy`, so I open another terminal and do this:

```
➤ docker container exec -it proxy ps
PID   USER     TIME   COMMAND
    1 root       0:00 /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.p
    8 root       0:00 syslogd -nLO-
    9 root       0:00 /usr/local/sbin/haproxy-master
   10 root       0:00 /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local
   99 root       0:00 ps

➤ docker container exec -it proxy pstree -p
haproxy-systemd(1)-+-haproxy(9)---haproxy(10)
                   `-syslogd(8)
```

As you can observe, there's no `sh` or `/docker-entypoint.sh` command. Also, PID 1 is the HAProxy command itself (this `haproxy-systemd-wrapper` thing is a little magic the image has, and it's what it's expected to be).

Docker automatically sends all signals to PID 1, always. Thaks to `exec`, that means that `haproxy-systemd-wrapper` will catch all signals properly. When PID 1 exits, Docker automatically will reap all other remaining PIDs in the container, if any, so no need to over-engineer here.

And if you don't believe me, just kill the container with a `HUP` signal (which instructs HAProxy to do a soft reload):

```
docker container kill -s HUP proxy
```

If you are attached to logs in the 1st terminal, you will see that the container did not exit, syslogd kept running, old `haproxy-master` and `haproxy` commands disappeared and got replaced by new ones (you can check that by running `ps` before and after the kill and checking both processes have different PID).

> this would force docker stop to just kill it after the 10 second timeout

Indeed, if you `docker stop` it, it will have to kill syslogd. However that's not a bug, that's the expected behavior.

This is because if you really expect zero downtime in your proxy, you'd be sending a `docker container kill -s HUP` instead, as said above. If you `docker stop` it, you are *expecting some seconds of downtime*, so there you have them: 10 seconds.

No need to do anything else here.

> There is nothing watching the syslogd process to ensure it stays running, so it could crash and you would no longer get any logs.

This is out of scope of this image, because:

1. There's no reason why that process would magically crash.
2. If you really need more fine-grained control on syslogd, then run it on another container.

We don't need to over-engineer here.

There are a lots of misconceptions floating around the Internet about how Docker handles processes, signals, and reaps or not children, but don't believe everything you read; just check what I said, that's how it really works. 😉

**Comment by tianon** [comment]
@Yajo I think it's worth noting that I've watched @yosifkit spend literal hours debugging this, and it really isn't quite so simple (hence his working on a simple pass-through that only implements syslog).  I think showing a concrete example of the broken behavior with this approach will help clear things up:

Behavior before changing anything:
```console
$ cat haproxy.cfg
defaults
	log /dev/log local0
	log /dev/log local1 notice
	mode http
	timeout connect 5000ms
	timeout client 50000ms
	timeout server 50000ms
listen test
	bind *:80

$ docker run --name test -dit -v "$PWD/haproxy.cfg":/usr/local/etc/haproxy/haproxy.cfg haproxy:alpine
1c9d5525cc7d8e3b9c0df086662ff521820800fe596fc00835f946d4fbf93c04

$ docker logs test
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
[ALERT] 094/200305 (8) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 094/200305 (8) : sendmsg logger #2 failed: No such file or directory (errno=2)

$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                22245               22218               0                   13:03               pts/22              00:00:00            /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg
root                22587               22245               0                   13:03               pts/22              00:00:00            /usr/local/sbin/haproxy-master
root                22729               22587               0                   13:03               ?                   00:00:00            /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds

$ docker kill -s TERM test
test

$ docker top test
Error response from daemon: Container 1c9d5525cc7d8e3b9c0df086662ff521820800fe596fc00835f946d4fbf93c04 is not running
```

Great, `SIGTERM` successfully stopped the container gracefully, as expected.

Now again, but with the following change (to start `syslogd` in the background; built as `haproxy:syslogd`):

```diff
$ git diff
diff --git a/1.7/alpine/docker-entrypoint.sh b/1.7/alpine/docker-entrypoint.sh
index 1b413a9..8577838 100755
--- a/1.7/alpine/docker-entrypoint.sh
+++ b/1.7/alpine/docker-entrypoint.sh
@@ -10,6 +10,7 @@ if [ "$1" = 'haproxy' ]; then
        # if the user wants "haproxy", let's use "haproxy-systemd-wrapper" instead so we can have proper reloadability implemented by upstream
        shift # "haproxy"
        set -- "$(which haproxy-systemd-wrapper)" -p /run/haproxy.pid "$@"
+       syslogd -O /proc/1/fd/1 -S -D
 fi
 
 exec "$@"
```
```console
$ docker run --name test -dit -v "$PWD/haproxy.cfg":/usr/local/etc/haproxy/haproxy.cfg haproxy:syslogd
e985d907c15f505d48fae5c65f7a7a22eae3630b4603785a235604d759cdc473

$ docker logs test
<7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
Apr  5 20:04:16 syslogd started: BusyBox v1.25.1
Apr  5 20:04:16 haproxy[10]: Proxy test started.
Apr  5 20:04:16 haproxy[10]: Proxy test started.

$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                28165               28149               0                   13:04               pts/22              00:00:00            /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg
root                28188               28165               0                   13:04               ?                   00:00:00            syslogd -O /proc/1/fd/1 -S -D
root                28189               28165               0                   13:04               pts/22              00:00:00            /usr/local/sbin/haproxy-master
root                28206               28189               0                   13:04               ?                   00:00:00            /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds

$ docker kill -s TERM test
test

$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                28165               28149               0                   13:04               pts/22              00:00:00            /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg
root                28188               28165               0                   13:04               ?                   00:00:00            syslogd -O /proc/1/fd/1 -S -D
```

Notice that the container no longer exits cleanly, because the extra `syslogd` process has confused `haproxy-systemd-wrapper` (being that it is a child of the former having replaced our shell).

**Comment by Yajo** [comment]
Sorry friend, I just tested with my PR your commands and they worked as expected.

I think the main difference is that you're adding this:

    syslogd -O /proc/1/fd/1 -S -D

While I add this:

    syslogd -nLO- &

Could you try with this PR and confirm if it works as expected, please?

BTW thanks for the ellaboration 😊

**Comment by Yajo** [comment]
OH sorry I have noticed I was missing the `-e SYSLOGD=1` parameter for my tests. Indeed results are the same as you explained.

**Comment by Yajo** [comment]
I observed that [`haproxy-systemd-wrapper` only intercepts 4 signals:](https://github.com/haproxy/haproxy/blob/master/src/haproxy-systemd-wrapper.c#L183-L209)

- `USR2` - restart
- `HUP` - restart
- `INT` - finish
- `TERM` - finish

We could add traps for those 4 signals and:

1. If `INT` or `TERM`, finish the `syslogd` process.
2. In any case, pass the signal to the underlying `haproxy-systemd-wrapper` process.

Of course, all of this only if `$SYSLOGD==1`. Otherwise, change nothing.

This would mean dropping `exec` too, of course. What do you think?

**Comment by Yajo** [comment]
I rebased and added https://github.com/Yelp/dumb-init to be able to safely add the syslogd subprocess. Concerns should be fixed now AFAIK... 🤔

**Comment by yosifkit** [comment]
`dumb-init` only "fixes" the dying problem because of the [session handling](https://github.com/Yelp/dumb-init/tree/d283f8a58bea8374c03becf8f06339670f2f07ee#session-behavior) it has.  This is just covering the issue rather than fixing it; it will kill it yes (since it forwards the signal to the entire process group), but doesn't really manage the life-cycle of syslog.  We are not going to have a second process in the container that is not fully managed by the pid 1 of the container.

Scenario using your image with dumb-init (since both `HUP` and `USR2` can be used to [restart haproxy](https://github.com/haproxy/haproxy/blob/25f067ccec52f53b0248a05caceb7841a3cb99df/src/haproxy-systemd-wrapper.c#L211)), but when syslogd gets the `USR2` it exits. (same haproxy.cfg as tianon's example above).
```console
$ docker run --name test -dit -v "$PWD/haproxy.cfg":/usr/local/etc/haproxy/haproxy.cfg -e SYSLOGD=1 haproxy:syslog
b9110e97c6463b7f031bd4d53ca9ee0ae32575d2946e277fc713ba900b753b74
$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                14956               14933               1                   14:24               ?                   00:00:00            /usr/local/bin/dumb-init -- /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg
root                15083               14956               0                   14:24               pts/0               00:00:00            /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg
root                15085               15083               0                   14:24               pts/0               00:00:00            syslogd -nLO-
root                15086               15083               0                   14:24               pts/0               00:00:00            /usr/local/sbin/haproxy-master
root                15088               15086               0                   14:24               ?                   00:00:00            /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds
$ docker kill -s USR2 test
test
$ docker top test
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                14956               14933               0                   14:24               ?                   00:00:00            /usr/local/bin/dumb-init -- /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg
root                15083               14956               0                   14:24               pts/0               00:00:00            /usr/local/sbin/haproxy-systemd-wrapper -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg
root                17689               15083               0                   14:24               pts/0               00:00:00            /usr/local/sbin/haproxy-master
root                17693               17689               0                   14:24               ?                   00:00:00            /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds -sf 15
```

**Comment by Yajo** [comment]
Thanks @yosifkit, I think the problem should be fixed with last commit, which also wraps syslogd process behind another dumb-init that ignores those signals.

**Comment by yosifkit** [comment]
Finally getting back around to this. :disappointed: :bowing_man: Sorry for the long tail.

I am still against using dumb-init since it hides the problem without fixing it. Also, they currently only release for one architecture (amd64) while we use the same Dockerfile to build for 7 architectures ([`amd64`](https://hub.docker.com/r/amd64/haproxy/), [`arm32v5`](https://hub.docker.com/r/arm32v5/haproxy/), [`arm32v7`](https://hub.docker.com/r/arm32v7/haproxy/), [`arm64v8`](https://hub.docker.com/r/arm64v8/haproxy/), [`i386`](https://hub.docker.com/r/i386/haproxy/), [`ppc64le`](https://hub.docker.com/r/ppc64le/haproxy/), [`s390x`](https://hub.docker.com/r/s390x/haproxy/)). All can be pulled via `docker pull haproxy` and it will resolve to pull the correct architecture-specific image.

----------------------------------

> > There is nothing watching the syslogd process to ensure it stays running, so it could crash and you would no longer get any logs.
>
> This is out of scope of this image, because:
>
> 1. There's no reason why that process would magically crash.
> 1. If you really need more fine-grained control on syslogd, then run it on another container.

This is not out of scope of the official images. As a rule, we do not run secondary processes (like syslog) in a container. If there were an exception, it would require a supervisor process monitoring the two processes in the container.  This supervisor would either start anew the offending process or exit the whole container (to allow a scheduler like Kubernetes or swarm to reschedule it) with the supervisor process deciding whether restart or exit is the correct response to the unexpected death of a child process.  Even if this is rare/impossible, the official images, along with being a useful starting point, are meant to be prime examples of [Dockerization](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/).

As to point two, there isn't a way to run syslog in another container using `/dev/log` since it is not possible to share it in a `volumes-from`. You could adjust it to some other folder that then contains the `log` socket, but that would require adjusting your haproxy config as well. If running syslog on the host, you could also use that with `-v /dev/log:/dev/log`.

**Comment by daveisfera** [comment]
Not being able to see the log output from the container is a real concern. A solution in the official images to work around this would be good. For the time being, we use this with the alpine image because it allows for SIGTERM to be forwarded to haproxy and the log output to be seen:

```
#!/usr/bin/env sh

_term() {
  echo "SIGTERM signal received"
  kill -TERM "${haproxychild}" 2>/dev/null
}

trap _term SIGTERM

echo "Starting syslogd..."
/sbin/syslogd -O /dev/stdout

echo "Starting haproxy..."
haproxy -f /etc/haproxy/haproxy.cfg &
haproxychild=$!

echo "Waiting for haproxy: ${haproxychild}"
wait ${haproxychild}
echo "Done"
```

**Comment by Yajo** [comment]
> Not being able to see the log output from the container is a real concern

Yes, that's my point. I know this one diverges a little bit from the usual docker configuration, but it's just because HAProxy is so special that it doesn't write to stdout. I have put all of this special behavior under a special env variable that is not meant to be enabled by default for that reason.

So, let's get practical @yosifkit: how do we fix this? 😅

**Comment by yosifkit** [comment]
I see a few options for a solution:

 1. tell users to use host syslog `docker run -v /dev/log:/dev/log haproxy` (assuming they have a config built in to their image)
 1. find a supervisor/init style process that will do the following:
    - forward signals to haproxy process
    - exits when haproxy dies, with haproxy's exit code
    - runs syslogd to write to stdout
    - manages syslogd's lifecycle
      - start it before haproxy
      - stop it when hapoxy stops
      - restart it if it unexpectedly stops
 1. continue development of https://github.com/yosifkit/syslog-init
    - @tianon was running into concurrency bugs during shutdown of the contianer like trying to ensure `/dev/log` was empty
    - will be extra maintenance burden
 1. evaluate using a "simple" series of bash scripts with traps (expand on @daveisfera's [example](https://github.com/docker-library/haproxy/pull/39#issuecomment-337765887) above)
    - needs to fulfill all the requirements of number 2

**Comment by jkrauska** [comment]
Hoping to reopen, as this never really got 'solved' and is a persistent problem for folks wanting to use haproxy in docker.

**Comment by nailgun** [comment]
Please checkout [solution](https://github.com/smpio/opendkim-docker/blob/master/entrypoint.sh#L6) I used for opendkim. It is one-liner and requires only `socat`:

`socat UNIX-RECV:/dev/log,mode=666 STDOUT &` invoked from entrypoint script spawns background process that will be terminated with main process.

**Comment by wstrange** [comment]
Any update on this PR? 

The haproxy docker image really needs out of box working solution...

**Comment by tianon** [comment]
I agree that a solution would be great to have, but I disagree that an acceptable one has been proposed.  This quirk of HAProxy is a major pain point for users especially in Docker, but it is a faithful representation of HAProxy (and has proven difficult and error prone to provide a stable solution for within a single container).

At this point, I'm wondering if we'd have better luck convincing HAProxy upstream to implement a means by which to log to stdout and/or stderr as an alternative to syslog (it would certainly be 100x more reliable / maintainable than anything proposed here so far).

Has anything like this been proposed upstream before?  Anyone know the appropriate places to check?

**Comment by lukastribus** [comment]
upstream is aware, but it's non-trivial due to the slow reader problem: neither dropping logs nor blocking the event loop is acceptable. The developers have something in mind, but there is no ETA:

https://www.mail-archive.com/haproxy@formilux.org/msg31653.html

**Comment by TimWolla** [comment]
Support for logging to stdout will be in haproxy 1.9, but appears to be discouraged still: haproxy/haproxy@5a32ecc6cf035468f119a7556d64f5cb6e8d11d1

For me personally haproxy is the only service I intentionally don't run in a container, because I trust it.

**Comment by yosifkit** [comment]
Closing as `1.9.0` added support for "logging to existing file descriptors" (aka stdout) and is now GA. It will be available on the Docker Hub shortly.

**Pull request closed without merging**
