### PR TITLE
Update to 1.7.13

### PR DESCRIPTION
**Pull request by TimWolla**
For some reason the bot did not pick this up.

### CODE REVIEW

**Comment by tianon** [comment]
The Alpine-related build failures here are the underlying reason why the bot "missed" both this and #146. :grimacing:

(We have a newer pattern for `update.sh` that we've implemented in other repositories that helps us do piecemeal updates which would avoid things like #146 getting delayed thanks to this build failure, but we obviously haven't implemented that here yet. :sweat_smile:)

**Comment by tianon** [comment]
The failure looks like it's the same underlying issue as https://github.com/haproxy/haproxy/issues/760, now backported to 1.7. :smile:

**Comment by TimWolla** [comment]
> The failure looks like it's the same underlying issue as [haproxy/haproxy#760](https://github.com/haproxy/haproxy/issues/760)

Ah, yeah. I remember. I've reopened that issue.

**Comment by tianon** [comment]
I rebased this on top of #148 and added a new commit to re-apply the patch for https://github.com/haproxy/haproxy/issues/760 (similar to #126 + #128).

**Comment by TimWolla** [comment]
> I rebased this […]

ack. That's why I leave the "allow maintainer pushes" enabled. Thanks!

**Pull request merged**
