### PR TITLE
Add HAProxy 2.5 / 2.6-rc

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by TimWolla** [comment]
Build failure does not appear to me my fault :weary:

**Comment by tianon** [comment]
There should be some tagging updates here too, right? :innocent:

https://github.com/docker-library/haproxy/blob/de6408459b0df546722793eb8dd8c6838bc479d0/generate-stackbrew-library.sh#L4-L7

```bash
# https://www.haproxy.org/ ("LTS" vs latest)
declare -A aliases=(
	[2.5]='latest'
	[2.4]='lts'
)
```

**Comment by TimWolla** [comment]
> There should be some tagging updates here too, right? innocent

Sure should. Now is.

**Review by tianon — APPROVED** [review]
Thanks :smile:

**Comment by yosifkit** [comment]
> there is also 2.4.9 that just went out

https://github.com/docker-library/official-images/pull/11386

**Pull request merged**
