### PR TITLE
Update 2.3 to 2.3.9

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by tianon** [comment]
(If I notice this finished with the build test faster than https://doi-janky.infosiftr.net/job/update.sh/job/haproxy/6640/console does, I plan to merge this instead of waiting for the bot :+1: :heart:  Thank you!)

**Review by wdauchy — APPROVED** [review]

**Comment by tianon** [comment]
Normally you're definitely spot on -- I just happened to be looking at the exact right moment. :joy:

You still managed to beat the bot though! :+1:

(The tests here run with better parallelism than the bot easily can. :sweat_smile:)

**Comment by tianon** [comment]
Indeed: https://github.com/docker-library/official-images/pull/9886 :+1:

**Comment by wdauchy** [comment]
wow, thanks!

**Pull request merged**
