### PR TITLE
Update to 2.3.8

### PR DESCRIPTION
**Pull request by TimWolla**
Assuming that the bot still is broken due to 1.7, here's a PR for the new 2.3.8 release.

### CODE REVIEW

**Review by wdauchy — APPROVED** [review]

**Comment by tianon** [comment]
Thanks!

**Comment by wdauchy** [comment]
Do you also take care of the official-images update?

**Comment by TimWolla** [comment]
Don't plan to. These are usually handled by tianon / the DOI team themselves. I believe there also exists some kind of automation for it.

**Comment by tianon** [comment]
Sorry for the delay -- PR is up at https://github.com/docker-library/official-images/pull/9864 (and automation was adjusted in #148 so we can avoid delays like this more easily in the future).

**Pull request merged**
